version: "3.7"

services:
  laravel-app:
    build: .
    ports:
      - "8501:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - dossie

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "8500:3306"
    volumes:
#     - dossie_volume:/var/lib/mysql
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    command:
      'mysqld --innodb-flush-method=fsync'
    networks:
      - dossie

networks:
  dossie:
    driver: bridge

volumes:
  dossie_volume: {}
